# Generated by Django 3.2.4 on 2021-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('rutFormulario', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut Formulario')),
                ('nombreFormulario', models.CharField(max_length=50, verbose_name='Nombre Formulario')),
                ('mailFormulario', models.CharField(max_length=60, verbose_name='e-Mail de')),
                ('passFormulario', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('celnumFormulario', models.IntegerField(verbose_name='Contraseña')),
            ],
        ),
    ]
