# Generated by Django 3.2.4 on 2021-06-23 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ciudadFormulario',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='comunaFormulario',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='dirFormulario',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='metodFormulario',
            field=models.CharField(default=1, max_length=100, verbose_name='Metodo de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='regionFormulario',
            field=models.CharField(default=1, max_length=50, verbose_name='Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='celnumFormulario',
            field=models.IntegerField(verbose_name='Numero Telefonico'),
        ),
    ]
